"""completar_der_semana_2

Revision ID: 54401b002565
Revises: 92eecd63a1dc
Create Date: 2026-06-29 00:37:57.413448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '54401b002565'
down_revision: Union[str, Sequence[str], None] = '92eecd63a1dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_procesos_id'), table_name='procesos')
    op.drop_table('procesos')
    op.add_column('documentos', sa.Column('tipo', sa.String(length=100), nullable=True))
    op.add_column('documentos', sa.Column('ruta_archivo', sa.String(length=512), nullable=False))
    op.alter_column('documentos', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documentos', 'nombre_archivo')
    op.drop_column('documentos', 'url_archivo')
    op.drop_column('documentos', 'fecha_subida')
    op.drop_column('documentos', 'tipo_documento')
    op.add_column('evaluaciones', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('evaluaciones', sa.Column('estado', sa.String(length=50), nullable=True))
    op.alter_column('evaluaciones', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('evaluaciones_evaluador_id_fkey'), 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(None, 'evaluaciones', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('evaluaciones', 'evaluador_id')
    op.drop_column('evaluaciones', 'fecha_evaluacion')
    op.drop_column('evaluaciones', 'puntaje_economico')
    op.drop_column('evaluaciones', 'puntaje_tecnico')
    op.add_column('ofertas', sa.Column('postulante_id', sa.Integer(), nullable=False))
    op.add_column('ofertas', sa.Column('fecha_presentacion', sa.DateTime(), nullable=True))
    op.alter_column('ofertas', 'proceso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('unique_usuario_proceso'), 'ofertas', type_='unique')
    op.create_unique_constraint('unique_postulante_proceso', 'ofertas', ['postulante_id', 'proceso_id'])
    op.drop_constraint(op.f('ofertas_proceso_id_fkey'), 'ofertas', type_='foreignkey')
    op.drop_constraint(op.f('ofertas_usuario_id_fkey'), 'ofertas', type_='foreignkey')
    op.create_foreign_key(None, 'ofertas', 'procesos_seleccion', ['proceso_id'], ['id'])
    op.create_foreign_key(None, 'ofertas', 'postulantes', ['postulante_id'], ['id'])
    op.drop_column('ofertas', 'usuario_id')
    op.drop_column('ofertas', 'propuesta_economica')
    op.drop_column('ofertas', 'fecha_envio')
    op.drop_column('ofertas', 'propuesta_tecnica')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ofertas', sa.Column('propuesta_tecnica', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('ofertas', sa.Column('fecha_envio', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('ofertas', sa.Column('propuesta_economica', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True))
    op.add_column('ofertas', sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.create_foreign_key(op.f('ofertas_usuario_id_fkey'), 'ofertas', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(op.f('ofertas_proceso_id_fkey'), 'ofertas', 'procesos', ['proceso_id'], ['id'])
    op.drop_constraint('unique_postulante_proceso', 'ofertas', type_='unique')
    op.create_unique_constraint(op.f('unique_usuario_proceso'), 'ofertas', ['usuario_id', 'proceso_id'])
    op.alter_column('ofertas', 'proceso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ofertas', 'fecha_presentacion')
    op.drop_column('ofertas', 'postulante_id')
    op.add_column('evaluaciones', sa.Column('puntaje_tecnico', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('evaluaciones', sa.Column('puntaje_economico', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True))
    op.add_column('evaluaciones', sa.Column('fecha_evaluacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('evaluaciones', sa.Column('evaluador_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(op.f('evaluaciones_evaluador_id_fkey'), 'evaluaciones', 'usuarios', ['evaluador_id'], ['id'])
    op.alter_column('evaluaciones', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('evaluaciones', 'estado')
    op.drop_column('evaluaciones', 'usuario_id')
    op.add_column('documentos', sa.Column('tipo_documento', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('fecha_subida', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('url_archivo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('documentos', sa.Column('nombre_archivo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.alter_column('documentos', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documentos', 'ruta_archivo')
    op.drop_column('documentos', 'tipo')
    op.create_table('procesos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('descripcion', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('creado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fecha_creacion', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], name=op.f('procesos_creado_por_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('procesos_pkey'))
    )
    op.create_index(op.f('ix_procesos_id'), 'procesos', ['id'], unique=False)
    # ### end Alembic commands ###
