"""init

Revision ID: 793cd2f1ffcd
Revises: 4ed137446ca2
Create Date: 2026-06-28 04:11:04.757271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '793cd2f1ffcd'
down_revision: Union[str, Sequence[str], None] = '4ed137446ca2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('procesos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesos_id'), 'procesos', ['id'], unique=False)
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('proceso_id', sa.Integer(), nullable=True),
    sa.Column('propuesta_tecnica', sa.Text(), nullable=True),
    sa.Column('propuesta_economica', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id', 'proceso_id', name='unique_usuario_proceso')
    )
    op.create_index(op.f('ix_ofertas_id'), 'ofertas', ['id'], unique=False)
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('nombre_archivo', sa.String(length=255), nullable=True),
    sa.Column('tipo_documento', sa.String(length=100), nullable=True),
    sa.Column('url_archivo', sa.Text(), nullable=True),
    sa.Column('fecha_subida', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documentos_id'), 'documentos', ['id'], unique=False)
    op.create_table('evaluaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=True),
    sa.Column('evaluador_id', sa.Integer(), nullable=True),
    sa.Column('puntaje_tecnico', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_economico', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('puntaje_total', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_evaluacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluaciones_id'), 'evaluaciones', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluaciones_id'), table_name='evaluaciones')
    op.drop_table('evaluaciones')
    op.drop_index(op.f('ix_documentos_id'), table_name='documentos')
    op.drop_table('documentos')
    op.drop_index(op.f('ix_ofertas_id'), table_name='ofertas')
    op.drop_table('ofertas')
    op.drop_index(op.f('ix_procesos_id'), table_name='procesos')
    op.drop_table('procesos')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
