"""init

Revision ID: 92eecd63a1dc
Revises: 32050d46dead
Create Date: 2026-06-28 21:34:47.346425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92eecd63a1dc'
down_revision: Union[str, Sequence[str], None] = '32050d46dead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entidades_contratantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entidades_contratantes_id'), 'entidades_contratantes', ['id'], unique=False)
    op.create_index(op.f('ix_entidades_contratantes_ruc'), 'entidades_contratantes', ['ruc'], unique=True)
    op.create_table('postulantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=11), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postulantes_id'), 'postulantes', ['id'], unique=False)
    op.create_index(op.f('ix_postulantes_ruc'), 'postulantes', ['ruc'], unique=True)
    op.create_table('procesos_seleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entidad_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=50), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entidad_id'], ['entidades_contratantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesos_seleccion_codigo'), 'procesos_seleccion', ['codigo'], unique=True)
    op.create_index(op.f('ix_procesos_seleccion_id'), 'procesos_seleccion', ['id'], unique=False)
    op.create_table('factores_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('puntaje_maximo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_seleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factores_evaluacion_id'), 'factores_evaluacion', ['id'], unique=False)
    op.create_table('reglas_validacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('severidad', sa.String(length=50), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_seleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reglas_validacion_id'), 'reglas_validacion', ['id'], unique=False)
    op.create_table('requisitos_calificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('obligatorio', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_seleccion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitos_calificacion_id'), 'requisitos_calificacion', ['id'], unique=False)
    op.create_table('tdr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('ruta_archivo', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos_seleccion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso_id')
    )
    op.create_index(op.f('ix_tdr_id'), 'tdr', ['id'], unique=False)
    op.create_table('personal_clave',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('experiencia', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_clave_id'), 'personal_clave', ['id'], unique=False)
    op.create_table('propuestas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('ruta_archivo', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propuestas_id'), 'propuestas', ['id'], unique=False)
    op.create_table('requisitos_tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tdr_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=255), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tdr_id'], ['tdr.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requisitos_tecnicos_id'), 'requisitos_tecnicos', ['id'], unique=False)
    op.create_table('detalle_evaluacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluacion_id', sa.Integer(), nullable=False),
    sa.Column('factor_id', sa.Integer(), nullable=False),
    sa.Column('puntaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['evaluacion_id'], ['evaluaciones.id'], ),
    sa.ForeignKeyConstraint(['factor_id'], ['factores_evaluacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_evaluacion_id'), 'detalle_evaluacion', ['id'], unique=False)
    op.drop_index(op.f('ix_procesos_id'), table_name='procesos')
    op.drop_table('procesos')
    op.add_column('documentos', sa.Column('tipo', sa.String(length=100), nullable=True))
    op.add_column('documentos', sa.Column('ruta_archivo', sa.String(length=512), nullable=False))
    op.alter_column('documentos', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('documentos', 'fecha_subida')
    op.drop_column('documentos', 'tipo_documento')
    op.drop_column('documentos', 'nombre_archivo')
    op.drop_column('documentos', 'url_archivo')
    op.add_column('evaluaciones', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.add_column('evaluaciones', sa.Column('estado', sa.String(length=50), nullable=True))
    op.alter_column('evaluaciones', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(None, 'evaluaciones', 'usuarios', ['usuario_id'], ['id'])
    op.drop_column('evaluaciones', 'evaluador_id')
    op.drop_column('evaluaciones', 'fecha_evaluacion')
    op.drop_column('evaluaciones', 'puntaje_economico')
    op.drop_column('evaluaciones', 'puntaje_tecnico')
    op.add_column('ofertas', sa.Column('postulante_id', sa.Integer(), nullable=False))
    op.add_column('ofertas', sa.Column('fecha_presentacion', sa.DateTime(), nullable=True))
    op.alter_column('ofertas', 'proceso_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('unique_usuario_proceso'), 'ofertas', type_='unique')
    op.create_unique_constraint('unique_postulante_proceso', 'ofertas', ['postulante_id', 'proceso_id'])
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.create_foreign_key(None, 'ofertas', 'procesos_seleccion', ['proceso_id'], ['id'])
    op.create_foreign_key(None, 'ofertas', 'postulantes', ['postulante_id'], ['id'])
    op.drop_column('ofertas', 'usuario_id')
    op.drop_column('ofertas', 'propuesta_economica')
    op.drop_column('ofertas', 'propuesta_tecnica')
    op.drop_column('ofertas', 'fecha_envio')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ofertas', sa.Column('fecha_envio', sa.DATETIME(), nullable=True))
    op.add_column('ofertas', sa.Column('propuesta_tecnica', sa.TEXT(), nullable=True))
    op.add_column('ofertas', sa.Column('propuesta_economica', sa.NUMERIC(precision=12, scale=2), nullable=True))
    op.add_column('ofertas', sa.Column('usuario_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.drop_constraint(None, 'ofertas', type_='foreignkey')
    op.create_foreign_key(None, 'ofertas', 'usuarios', ['usuario_id'], ['id'])
    op.create_foreign_key(None, 'ofertas', 'procesos', ['proceso_id'], ['id'])
    op.drop_constraint('unique_postulante_proceso', 'ofertas', type_='unique')
    op.create_unique_constraint(op.f('unique_usuario_proceso'), 'ofertas', ['usuario_id', 'proceso_id'])
    op.alter_column('ofertas', 'proceso_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('ofertas', 'fecha_presentacion')
    op.drop_column('ofertas', 'postulante_id')
    op.add_column('evaluaciones', sa.Column('puntaje_tecnico', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.add_column('evaluaciones', sa.Column('puntaje_economico', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.add_column('evaluaciones', sa.Column('fecha_evaluacion', sa.DATETIME(), nullable=True))
    op.add_column('evaluaciones', sa.Column('evaluador_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'evaluaciones', type_='foreignkey')
    op.create_foreign_key(None, 'evaluaciones', 'usuarios', ['evaluador_id'], ['id'])
    op.alter_column('evaluaciones', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('evaluaciones', 'estado')
    op.drop_column('evaluaciones', 'usuario_id')
    op.add_column('documentos', sa.Column('url_archivo', sa.TEXT(), nullable=True))
    op.add_column('documentos', sa.Column('nombre_archivo', sa.VARCHAR(length=255), nullable=True))
    op.add_column('documentos', sa.Column('tipo_documento', sa.VARCHAR(length=100), nullable=True))
    op.add_column('documentos', sa.Column('fecha_subida', sa.DATETIME(), nullable=True))
    op.alter_column('documentos', 'oferta_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('documentos', 'ruta_archivo')
    op.drop_column('documentos', 'tipo')
    op.create_table('procesos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=255), nullable=False),
    sa.Column('descripcion', sa.TEXT(), nullable=True),
    sa.Column('fecha_inicio', sa.DATE(), nullable=False),
    sa.Column('fecha_fin', sa.DATE(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=50), nullable=True),
    sa.Column('creado_por', sa.INTEGER(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_procesos_id'), 'procesos', ['id'], unique=False)
    op.drop_index(op.f('ix_detalle_evaluacion_id'), table_name='detalle_evaluacion')
    op.drop_table('detalle_evaluacion')
    op.drop_index(op.f('ix_requisitos_tecnicos_id'), table_name='requisitos_tecnicos')
    op.drop_table('requisitos_tecnicos')
    op.drop_index(op.f('ix_propuestas_id'), table_name='propuestas')
    op.drop_table('propuestas')
    op.drop_index(op.f('ix_personal_clave_id'), table_name='personal_clave')
    op.drop_table('personal_clave')
    op.drop_index(op.f('ix_tdr_id'), table_name='tdr')
    op.drop_table('tdr')
    op.drop_index(op.f('ix_requisitos_calificacion_id'), table_name='requisitos_calificacion')
    op.drop_table('requisitos_calificacion')
    op.drop_index(op.f('ix_reglas_validacion_id'), table_name='reglas_validacion')
    op.drop_table('reglas_validacion')
    op.drop_index(op.f('ix_factores_evaluacion_id'), table_name='factores_evaluacion')
    op.drop_table('factores_evaluacion')
    op.drop_index(op.f('ix_procesos_seleccion_id'), table_name='procesos_seleccion')
    op.drop_index(op.f('ix_procesos_seleccion_codigo'), table_name='procesos_seleccion')
    op.drop_table('procesos_seleccion')
    op.drop_index(op.f('ix_postulantes_ruc'), table_name='postulantes')
    op.drop_index(op.f('ix_postulantes_id'), table_name='postulantes')
    op.drop_table('postulantes')
    op.drop_index(op.f('ix_entidades_contratantes_ruc'), table_name='entidades_contratantes')
    op.drop_index(op.f('ix_entidades_contratantes_id'), table_name='entidades_contratantes')
    op.drop_table('entidades_contratantes')
    # ### end Alembic commands ###
